# Generated by Django 4.2.25 on 2025-10-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0003_cleanup_tlt_respuesta_indexes'),
    ]

    operations = [
    ]
