# Generated by Django 4.2.25 on 2025-10-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0004_cleanup_tlt_respuesta_indexes'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS idx_tlt_respuesta_sesion_ccp;",
            reverse_sql=(
                "CREATE INDEX IF NOT EXISTS idx_tlt_respuesta_sesion_ccp "
                "ON tlt_respuesta(sesion_id, ccp_code);"
            ),
        ),
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS idx_tlt_respuesta_sesion_ejer;",
            reverse_sql=(
                "CREATE INDEX IF NOT EXISTS idx_tlt_respuesta_sesion_ejer "
                "ON tlt_respuesta(sesion_id, ejer_code);"
            ),
        ),
    ]
