# Generated by Django 4.2.25 on 2025-10-19 13:14

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("runtime", "0005_drop_old_tlt_respuesta_indexes"),  # ajusta si tu última difiere
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "CREATE INDEX IF NOT EXISTS idx_tlt_respuesta_sesion_ccp_fecha "
                "ON tlt_respuesta(sesion_id, ccp_code, created_at);"
            ),
            reverse_sql=(
                "DROP INDEX IF EXISTS idx_tlt_respuesta_sesion_ccp_fecha;"
            ),
        ),
    ]
