# Generated by Django 4.2.25 on 2025-10-20 15:23

from django.db import migrations

SQL_FWD = """
CREATE INDEX IF NOT EXISTS idx_tlt_respuesta_sesion_ccp_fecha
ON tlt_respuesta (sesion_id, ccp_code, created_at);
"""

SQL_BWD = """
DROP INDEX IF EXISTS idx_tlt_respuesta_sesion_ccp_fecha;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0006_add_idx_sesion_ccp_fecha'),
    ]

    operations = [
        migrations.RunSQL(SQL_FWD, reverse_sql=SQL_BWD),
    ]
