# Generated by Django 4.2.25 on 2025-10-20 15:41

from django.db import migrations

SQL_VIEW_PANEL = """
DROP VIEW IF EXISTS v_panel_metrics;
CREATE VIEW v_panel_metrics AS
SELECT
    sesion_id,
    ccp_code,
    COUNT(*)                                                   AS n,
    SUM(CASE WHEN correcta IN (1, TRUE) THEN 1 ELSE 0 END)    AS aciertos,
    100.0 * SUM(CASE WHEN correcta IN (1, TRUE) THEN 1 ELSE 0 END) / COUNT(*) AS acierto_pct,
    AVG(tr_ms)                                                AS tr_ms_avg,
    MIN(created_at)                                           AS first_ts,
    MAX(created_at)                                           AS last_ts
FROM tlt_respuesta
GROUP BY sesion_id, ccp_code;
"""

SQL_VIEW_SESSION = """
DROP VIEW IF EXISTS v_panel_metrics_session;
CREATE VIEW v_panel_metrics_session AS
SELECT
    sesion_id,
    COUNT(*)                                                   AS n,
    SUM(CASE WHEN correcta IN (1, TRUE) THEN 1 ELSE 0 END)    AS aciertos,
    100.0 * SUM(CASE WHEN correcta IN (1, TRUE) THEN 1 ELSE 0 END) / COUNT(*) AS acierto_pct,
    AVG(tr_ms)                                                AS tr_ms_avg,
    MIN(created_at)                                           AS first_ts,
    MAX(created_at)                                           AS last_ts
FROM tlt_respuesta
GROUP BY sesion_id;
"""

class Migration(migrations.Migration):
    dependencies = [
        ("runtime", "0007_idx_tlt_respuesta"),  # ajusta si tu última difiere
    ]
    operations = [
        migrations.RunSQL(SQL_VIEW_PANEL, reverse_sql="DROP VIEW IF EXISTS v_panel_metrics;"),
        migrations.RunSQL(SQL_VIEW_SESSION, reverse_sql="DROP VIEW IF EXISTS v_panel_metrics_session;"),
    ]
