# Generated by Django 4.2.24 on 2025-09-25 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submodality', models.CharField(choices=[('VIS_S', 'Visual Simbólica'), ('VIS_I', 'Visual Icónica')], max_length=16)),
                ('difficulty_level', models.PositiveSmallIntegerField(default=1)),
                ('stimulus', models.JSONField()),
                ('options', models.JSONField()),
                ('correct_index', models.PositiveSmallIntegerField()),
                ('params', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('vpm_mode', models.CharField(choices=[('VIS_S', 'Visual Simbólica'), ('VIS_I', 'Visual Icónica')], max_length=16)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_ms', models.IntegerField()),
                ('responded_ms', models.IntegerField()),
                ('response_time_ms', models.IntegerField()),
                ('chosen_index', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('client_meta', models.JSONField(blank=True, default=dict)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccp_vpm.item')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='ccp_vpm.session')),
            ],
        ),
    ]
